import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import { QueryProvider } from '@/lib/QueryProvider'

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

const fontSans = Inter({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-inter',
})

type RootLayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={cn('bg-white font-sans text-slate-900 antialiased', fontSans.variable)}>
      <body className="min-h-screen">
        {/*<h1 className="pt-12 text-center text-2xl uppercase">Blog app nextjs</h1>*/}
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  )
}
